# Generated by Django 3.1.12 on 2025-03-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('rateByUser', models.FloatField(default=0)),
                ('rateByAi', models.FloatField(default=0)),
                ('rateAvg', models.FloatField(default=0)),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
