# Generated by Django 3.1.12 on 2025-03-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentimentType',
            field=models.CharField(default='positive', max_length=50),
        ),
    ]
