# Generated by Django 3.1.12 on 2025-06-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0)),
                ('methodPayment', models.CharField(default='cash', max_length=255)),
                ('statusPayment', models.CharField(default='pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
