# Generated by Django 3.1.12 on 2025-06-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('id_item', 'category')},
            },
        ),
    ]
