# Generated by Django 3.1.12 on 2025-03-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
