# Generated by Django 3.1.12 on 2025-03-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='book', max_length=255),
        ),
    ]
