# Generated by Django 3.1.12 on 2025-03-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
