# Generated by Django 3.1.12 on 2025-03-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_clothes_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='category',
            field=models.CharField(default='clothes', max_length=255),
        ),
    ]
